# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.0.0-rc4
  displayName: Install required tooling

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: |
    mkdir $(Build.SourcesDirectory)\test-results
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutput=$(Build.SourcesDirectory)\test-results\coverage test\IdentityServer.AspNetIdentity.Blazor.Client.UnitTests
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutput=$(Build.SourcesDirectory)\test-results\coverage /p:MergeWith=$(Build.SourcesDirectory)\test-results\coverage.json test\IdentityServer.AspNetIdentity.Server.UnitTests
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutput=$(Build.SourcesDirectory)\test-results\coverage /p:MergeWith=$(Build.SourcesDirectory)\test-results\coverage.json test\IdentityServer.AspNetIdentity.Server.IntegrationTests
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutput=$(Build.SourcesDirectory)\test-results\coverage /p:MergeWith=$(Build.SourcesDirectory)\test-results\coverage.json test\IdentityServer.Blazor.Admin.Client.UnitTests
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutput=$(Build.SourcesDirectory)\test-results\coverage /p:MergeWith=$(Build.SourcesDirectory)\test-results\coverage.json test\IdentityServer.Blazor.Admin.Server.UnitTests
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutput=$(Build.SourcesDirectory)\test-results\coverage /p:CoverletOutputFormat=cobertura /p:MergeWith=$(Build.SourcesDirectory)\test-results\coverage.json test\IdentityServer.Blazor.Admin.Server.IntegrationTests
    .\reportgenerator "-reports:$(Build.SourcesDirectory)\test-results\coverage.cobertura.xml" "-targetdir:test-results\Html" "-reporttypes:HTMLInline;HTMLChart"
  displayName: 'Unit and Integration tests'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: $(Build.SourcesDirectory)\test-results\coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)\test-results\Html
    codecoverageTool: cobertura